name: GitHub Actions Practise towards path properties on the.
on:
  push:
    branches:
      - master
    paths:
      - "js/**.js"
      - "!python/**.py"

jobs:
  log:
    # setting up a shared runner by github 
    runs-on: ubuntu-latest

    steps:
    # checking out repository.
      - name: checkout the repository
        uses: actions/checkout@v5
        with:
          node-version: "24.13.1"
        # run: echo "${{ toJSON(github) }}"

# just logging the msg to console with github context api details.
      - name: Logging the message to the console when we push .js files into js repo.
        run: |
          echo "new js file | change in the js file was triggered. Thank you."
          echo "${{ toJSON(github) }}"

